### ISSUE TITLE
Cant find 'application/config/assets.php'

### ISSUE THREAD

**Issue by amitpatil321** [GustMartins/Slice-Library#1]
I downloaded zip 'slice library' files and extracted, Where is 'application/config/assets.php this file located ? I cant find it inside config folder, only file i see is 'slice.php'.

**Comment by GustMartins** [comment]
I feel sorry about this mistake! 
You should use the **`slice.php`** file that is located inside config folder.

The 'application/config/assets.php' is **not** used in this project.
Soon, I will fix this bug!

So, to use the Slice-Library you must copy the file **`application/config/slice.php`** to your own `application/config/` folder and edit it according to your needs.
Now, copy the file `application/libraries/Slice.php` to your own `application/libraries/` folder. 
Finally, make sure the folder `application/cache/` has a **`0664`** permission to save the compiled templates the library will produce.

Thanks!

**Comment by amitpatil321** [comment]
Thanks for quick reply, will give it a try.
