### ISSUE TITLE
um...@include not working..

### ISSUE THREAD

**Issue by junaexp** [GustMartins/Slice-Library#10]
hi~!
You've created a really cool library!

------------

but, @include is not working... (my case)

## **[ just my code (for phpstorm syntax) ]**
```php
application/libraries/Slice.php -- 24
ㄴ public $slice_ext       = '.blade.php';

application/config/slice.php -- 19
ㄴ $config['slice_ext'] = '.blade.php';
```

## **[ view folder ]**
ㄴ main.blade.php
ㄴ main_modal.blade.php

## **[ main.blade.php ]**
`@include('main_modal')`

## **[error msg]**
![error](https://user-images.githubusercontent.com/21023621/38177395-c0edae88-363b-11e8-892f-881a34922415.png)

**Comment by Jarzebowsky** [comment]
You should pass path from root of views folder in app separated by dot (.) instead forward slash (/) - than it should work for you ;)

**Comment by junaexp** [comment]
@Jarzebowsky Sorry, I'm late...
anyway, It's WORK !!!

Many Thank's !!
