### ISSUE TITLE
I want use a variable in @yield..

### ISSUE THREAD

**Issue by otffotff** [GustMartins/Slice-Library#16]
**Describe the bug**
I want use a variable in @yield..

**To Reproduce**
1. There are just three files. (base.slice.php, content.slice.php, index.php)
    in base.slice.php
        @yield('title')
    in content.slice.php
        @section('title', '{{ $sub_title }}')
    in index.php 
         $data['sub_title'] = 'intro';
2. but it show empty data.. so I try @section('title', '<?= $sub_title ?>') .. same result..

**Expected behavior**
It must show 'intro' !!!

**Screenshots**
I think it's unnecessary.

**Versions (please complete the following information):**
 - PHP: PHP 5.6.40-1+ubuntu14.04.1+deb.sury.org+1 (cli)
 - CodeIgniter: 3.0.6
 - Slice: 1.3.0

**Additional context**
Could you give me your hand?

**Comment by gustmartins** [comment]
Hi @otffotff!

I don't understand why did you declare your variable in `index.php` file. A better approach is to set this variable with `$this->slice->with('sub_title', 'intro')` in your **controller**.

Then, you can use this variable in the file `content.slice.php` like this: `@section('title' $sub_title)`.

**Comment by otffotff** [comment]
Thanks @GustMartins 

I mean..  "$this->slice->view("content", $data);
It is solved by this => @section('title', $sub_title);
Thanks a lot~ I like slice !!! 👍
